### ISSUE TITLE
Class Error while accessing Craft Dashboard.

### ISSUE THREAD

**Issue by bhashkar007** [mediabeastnz/craft-commerce-abandoned-cart#47]
While going to Craft Dashboard, I am getting following error:
```
Error: Class 'craft\commerce\base\Stat' not found in /srv/app/craft3-77i2/htdocs/vendor/mediabeastnz/craft-commerce-abandoned-cart/src/stats/TotalCartsRecovered.php:13
Stack trace:
#0 /srv/app/craft3-77i2/htdocs/vendor/composer/ClassLoader.php(444): include()
#1 /srv/app/craft3-77i2/htdocs/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/srv/app/craft3...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('mediabeastnz\\ab...')
#3 /srv/app/craft3-77i2/htdocs/vendor/mediabeastnz/craft-commerce-abandoned-cart/src/widgets/TotalCartsRecovered.php(45): spl_autoload_call('mediabeastnz\\ab...')
#4 /srv/app/craft3-77i2/htdocs/vendor/yiisoft/yii2/base/BaseObject.php(109): mediabeastnz\abandonedcart\widgets\TotalCartsRecovered->init()
#5 [internal function]: yii\base\BaseObject->__construct(Array)
#6 /srv/app/craft3-77i2/htdocs/vendor/yiisoft/yii2/di/Container.php(398): ReflectionClass->newInstanceArgs(Array)
#7 /srv/app/craft3-77i2/htdocs/vendor/yiisoft/yii2/di/Container.php(165): yii\di\Container->build('mediabeastnz\\ab...', Array, Array)
#8 /srv/app/craft3-77i2/htdocs/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('mediabeastnz\\ab...', Array, Array)
#9 /srv/app/craft3-77i2/htdocs/vendor/craftcms/cms/src/helpers/Component.php(111): yii\BaseYii::createObject(Array)
#10 /srv/app/craft3-77i2/htdocs/vendor/craftcms/cms/src/services/Dashboard.php(119): craft\helpers\Component::createComponent(Array, 'craft\\base\\Widg...')
#11 /srv/app/craft3-77i2/htdocs/vendor/craftcms/cms/src/controllers/DashboardController.php(79): craft\services\Dashboard->createWidget(Array)
#12 [internal function]: craft\controllers\DashboardController->actionIndex()
#13 /srv/app/craft3-77i2/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /srv/app/craft3-77i2/htdocs/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#15 /srv/app/craft3-77i2/htdocs/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('index', Array)
#16 /srv/app/craft3-77i2/htdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#17 /srv/app/craft3-77i2/htdocs/vendor/craftcms/cms/src/web/Application.php(285): yii\base\Module->runAction('dashboard/index', Array)
#18 /srv/app/craft3-77i2/htdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#19 /srv/app/craft3-77i2/htdocs/vendor/craftcms/cms/src/web/Application.php(270): yii\web\Application->handleRequest(Object(craft\web\Request))
#20 /srv/app/craft3-77i2/htdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /srv/app/craft3-77i2/htdocs/public/index.php(22): yii\base\Application->run()
#22 {main}
```

Craft CMS v3.5.11.1
Craft Commerce v2.2.22
Abandoned Cart for Craft Commerce v1.6.2

Could you please help.

**Comment by mediabeastnz** [comment]
Hi @bhashkar007 i've just installed all those versions and the dashboard and widget is working as expected.

Can you maybe upgrade to the latest version of Commerce?

Also a few more questions for you:
- what PHP version?
- a you using craft pro and commerce pro?

**Comment by bhashkar007** [comment]
Hi @mediabeastnz 
Thanks for your response. 
- PHP v7.4.4
- Yes, I am using Craft Pro and Commerce Pro

**Comment by mediabeastnz** [comment]
I've tested these exact versions and it's working as expected.
Is there any additional information you can give me?

**Comment by bhashkar007** [comment]
Hi @mediabeastnz 
I can share Craft dashboard access. Please provide your email on which I can send login details. I guess, it will be quick for you to look into.

**Comment by mediabeastnz** [comment]
Hi @bhashkar007 the dashboard won't tell me too much - are you able to instead send me any log files from `storage/logs`.
I think you have my email address already.

**Comment by mediabeastnz** [comment]
Hi @bhashkar007 I've had a look through your log files but can't find anything that has more details on the issue you're having.

Is there anything special about your configuration that I might be missing as I've setup a fresh install and have had no issues.
